In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler 
# from sklearn.cluster import KMeans

In [ ]:
df_train = pd.read_csv('train.csv')
# df_train.head()

In [ ]:
df_test = pd.read_csv('test.csv')

In [ ]:
df_train.shape

(1460, 81)

In [ ]:
df_test.shape

(1459, 80)

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1459 non-null   int64  
 1   MSSubClass     1459 non-null   int64  
 2   MSZoning       1455 non-null   object 
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64  
 5   Street         1459 non-null   object 
 6   Alley          107 non-null    object 
 7   LotShape       1459 non-null   object 
 8   LandContour    1459 non-null   object 
 9   Utilities      1457 non-null   object 
 10  LotConfig      1459 non-null   object 
 11  LandSlope      1459 non-null   object 
 12  Neighborhood   1459 non-null   object 
 13  Condition1     1459 non-null   object 
 14  Condition2     1459 non-null   object 
 15  BldgType       1459 non-null   object 
 16  HouseStyle     1459 non-null   object 
 17  OverallQual    1459 non-null   int64  
 18  OverallC

In [ ]:
df_train.drop(['Alley','PoolQC','Fence','MiscFeature'],axis=1,inplace=True)

In [ ]:
df_test.drop(['Alley','PoolQC','Fence','MiscFeature'],axis=1,inplace=True)

In [ ]:
# df_train.drop(['Id'],axis=1,inplace=True)

In [ ]:
df_train.shape

(1460, 77)

In [ ]:
columns = list(df_train.columns)

In [ ]:
columns1 = list(df_test.columns)

In [ ]:
len(columns)

77

In [ ]:
for col in columns:
  if (df_train[col].dtype) == 'O':
    df_train[col] = df_train[col].fillna(df_train[col].mode()[0])

  elif (df_train[col].dtype) == 'float64' or 'int64':
    df_train[col] = df_train[col].fillna(df_train[col].mean())

In [ ]:
for col in columns1:
  if (df_test[col].dtype) == 'O':
    df_test[col] = df_test[col].fillna(df_test[col].mode()[0])

  elif (df_test[col].dtype) == 'float64' or 'int64':
    df_test[col] = df_test[col].fillna(df_train[col].mean())

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 77 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1459 non-null   int64  
 1   MSSubClass     1459 non-null   int64  
 2   MSZoning       1459 non-null   object 
 3   LotFrontage    1459 non-null   float64
 4   LotArea        1459 non-null   int64  
 5   Street         1459 non-null   object 
 6   LotShape       1459 non-null   object 
 7   LandContour    1459 non-null   object 
 8   Utilities      1459 non-null   object 
 9   LotConfig      1459 non-null   object 
 10  LandSlope      1459 non-null   object 
 11  Neighborhood   1459 non-null   object 
 12  Condition1     1459 non-null   object 
 13  Condition2     1459 non-null   object 
 14  BldgType       1459 non-null   object 
 15  HouseStyle     1459 non-null   object 
 16  OverallQual    1459 non-null   int64  
 17  OverallCond    1459 non-null   int64  
 18  YearBuil

In [ ]:
df_train.dropna(inplace=True)

In [ ]:
df_test.dropna(inplace=True)

In [ ]:
df_train.shape

(1460, 77)

In [ ]:
df_test.shape

(1459, 76)

In [ ]:
columns = list(df_train.columns)

In [ ]:
obj = []
for col in columns:
  if (df_train[col].dtype) == 'O':
    obj.append(col)

In [ ]:
len(obj)

39

In [ ]:
merged_df = pd.concat([df_train,df_test],axis=0)

In [ ]:
merged_df.shape

(2919, 77)

In [ ]:
merged_df['SalePrice']

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...   
1454         NaN
1455         NaN
1456         NaN
1457         NaN
1458         NaN
Name: SalePrice, Length: 2919, dtype: float64

In [ ]:
for col in obj:

  df = pd.get_dummies(merged_df[col],drop_first=True)
  merged_df.drop([col],inplace=True,axis=1)
  merged_df = pd.concat([merged_df,df],axis=1)

In [ ]:
merged_df.shape

(2919, 238)

In [ ]:
df_train1 = merged_df.iloc[:1460,:]

In [ ]:
df_test1 = merged_df.iloc[1460:2920,:]

In [ ]:
df_test1['SalePrice']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1454   NaN
1455   NaN
1456   NaN
1457   NaN
1458   NaN
Name: SalePrice, Length: 1459, dtype: float64

In [ ]:
df_train1['SalePrice']

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...   
1455    175000.0
1456    210000.0
1457    266500.0
1458    142125.0
1459    147500.0
Name: SalePrice, Length: 1460, dtype: float64

In [ ]:
df_train1 = df_train1.loc[:,~df_train1.columns.duplicated()]

In [ ]:
df_test1 = df_test1.loc[:,~df_test1.columns.duplicated()]

In [ ]:
df_test1.drop('SalePrice',axis=1,inplace=True)

In [ ]:
df_test1.shape

(1459, 177)

In [ ]:
df_train1.shape

(1460, 178)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

In [ ]:
X = df_train1.drop('SalePrice',axis=1)
Y = df_train1['SalePrice']

In [ ]:
X = StandardScaler().fit(X).transform(X)

In [ ]:
rfg = RandomForestRegressor()

In [ ]:
rfg.fit(X,Y)

RandomForestRegressor()

In [ ]:
X_test1 = StandardScaler().fit(df_test1).transform(df_test1)

In [ ]:
ypred_1 = rfg.predict(X_test1)
ypred_1[0:5]

array([130645.93, 155988.  , 186700.35, 183652.9 , 200144.3 ])

In [ ]:
mae = mean_absolute_error(y_true=ytest, y_pred=ypred_1)
mae

53907.85100170297

In [ ]:
df_sub = pd.read_csv('sample_submission.csv')
df_sub.head()

Id      SalePrice
0  1461  169277.052498
1  1462  187758.393989
2  1463  183583.683570
3  1464  179317.477511
4  1465  150730.079977

In [ ]:
df_sub_f = df_sub[['Id']]

In [ ]:
df_sub_f['SalePrice'] = ypred_1

In [ ]:
df_sub_f.to_csv('sub_dp.csv',index=False)

In [ ]:
# accuracy = []

# for i in range (0,10):
#   rfg = RandomForestRegressor()
#   X = StandardScaler().fit(X).transform(X)
  
#   X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size=1, random_state=42)

#   model = rfg.fit(X_train,Y_train)

#   ypred = model.predict(X_test)

#   mae = mean_absolute_error(y_true =Y_test, y_pred=ypred)
#   accuracy.append(mae)
#   print(f"Fold {i + 1}: MAE = {mae:.3f}")

# print(f"Average MAE: {(sum(accuracy) / len(accuracy)):.2f}")

In [ ]:
accuracy = []
for fold in range(0, 10):

  # Instantiate algorithm
  model = RandomForestRegressor()
  scaler = StandardScaler()

  # Create training and test samples
  X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.8, random_state=42)

  # Scale X data, we scale the data because it helps the algorithm to converge
  # and helps the algorithm to not be greedy with large values
  scaler.fit(X_train)
  X_train = scaler.transform(X_train)
  X_test = scaler.transform(X_test)

  # Train model
  trained_model = model.fit(X_train, y_train)

  # Generate predictions on test sample
  y_pred = trained_model.predict(X_test)

  # Compute accuracy, using mean absolute error
  mae = mean_absolute_error(y_true=y_test, y_pred=y_pred)
  accuracy.append(mae)
  print(f"Fold {fold + 1}: MAE = {mae:.3f}")

print(f"Average MAE: {(sum(accuracy) / len(accuracy)):.2f}")


Fold 1: MAE = 17994.787
Fold 2: MAE = 17636.657
Fold 3: MAE = 17703.625
Fold 4: MAE = 18001.867
Fold 5: MAE = 17991.698
Fold 6: MAE = 17836.612
Fold 7: MAE = 17760.280
Fold 8: MAE = 18017.168
Fold 9: MAE = 18011.817
Fold 10: MAE = 17962.807
Average MAE: 17891.73


In [ ]:
ypred_25 = trained_model.predict(X_test1)
ypred_25[0:5]

array([127778.83, 153835.5 , 181680.35, 186364.3 , 209920.49])

In [ ]:
mae = mean_absolute_error(y_true=ytest, y_pred=ypred_25)
mae 
# 53907.85100170297

53598.63820248857

In [ ]:
df_sub_ddp = df_sub[['Id']]

In [ ]:
df_sub_ddp['SalePrice'] = ypred_25

In [ ]:
# random_cv: 56168.33767283457
# random regressor without loop: 53907.85100170297
# random forest regressor with loop : 53598.63820248857

In [ ]:
df_sub_ddp

Id  SalePrice
0     1461  127778.83
1     1462  153835.50
2     1463  181680.35
3     1464  186364.30
4     1465  209920.49
...    ...        ...
1454  2915   90924.00
1455  2916   94740.00
1456  2917  159989.00
1457  2918  117273.00
1458  2919  238817.95

[1459 rows x 2 columns]

In [ ]:
df_sub_ddp.to_csv('submission_ddp.csv',index=False)

In [ ]:
import xgboost
regressor=xgboost.XGBRegressor()

In [ ]:
import xgboost
classifier=xgboost.XGBRegressor()

In [ ]:
booster=['gbtree','gblinear']
base_score=[0.25,0.5,0.75,1]

In [ ]:
## Hyper Parameter Optimization


n_estimators = [100, 500, 900, 1100, 1500]
max_depth = [2, 3, 5, 10, 15]
booster=['gbtree','gblinear']
learning_rate=[0.05,0.1,0.15,0.20]
min_child_weight=[1,2,3,4]

# Define the grid of hyperparameters to search
hyperparameter_grid = {
    'n_estimators': n_estimators,
    'max_depth':max_depth,
    'learning_rate':learning_rate,
    'min_child_weight':min_child_weight,
    'booster':booster,
    'base_score':base_score
    }

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
# Set up the random search with 4-fold cross validation
random_cv = RandomizedSearchCV(estimator=regressor,
            param_distributions=hyperparameter_grid,
            cv=5, n_iter=50,
            scoring = 'neg_mean_absolute_error',n_jobs = 4,
            verbose = 5, 
            return_train_score = True,
            random_state=42)

In [ ]:
random_cv.fit(X,Y)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[14:58:48] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


RandomizedSearchCV(cv=5, estimator=XGBRegressor(), n_iter=50, n_jobs=4,
                   param_distributions={'base_score': [0.25, 0.5, 0.75, 1],
                                        'booster': ['gbtree', 'gblinear'],
                                        'learning_rate': [0.05, 0.1, 0.15, 0.2],
                                        'max_depth': [2, 3, 5, 10, 15],
                                        'min_child_weight': [1, 2, 3, 4],
                                        'n_estimators': [100, 500, 900, 1100,
                                                         1500]},
                   random_state=42, return_train_score=True,
                   scoring='neg_mean_absolute_error', verbose=5)

In [ ]:
random_cv.best_estimator_

XGBRegressor(base_score=0.25, max_depth=2, n_estimators=900)

In [ ]:
random_cv.best_estimator_

XGBRegressor(base_score=0.25, max_depth=2, n_estimators=900)

In [ ]:
regressor=xgboost.XGBRegressor(base_score=0.25, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=2, min_child_weight=1, missing=None, n_estimators=900,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [ ]:
regressor.fit(X,Y)

XGBRegressor(base_score=0.25, max_depth=2, n_estimators=900, silent=True)

In [ ]:
ypred = regressor.predict(X_test1)

In [ ]:
ypred[0:5]

array([128052.766, 163448.16 , 182177.45 , 189346.53 , 194252.2  ],
      dtype=float32)

In [ ]:
len(ypred)

1459

In [ ]:
df_sub = pd.read_csv('sample_submission.csv')
df_sub.head()

Id      SalePrice
0  1461  169277.052498
1  1462  187758.393989
2  1463  183583.683570
3  1464  179317.477511
4  1465  150730.079977

In [ ]:
ytest = df_sub['SalePrice']

In [ ]:
mae = mean_absolute_error(y_true=ytest, y_pred=ypred)

In [ ]:
mae

56168.33767283457

Fold 1: MAE = 17713.294
Fold 2: MAE = 17896.233
Fold 3: MAE = 18196.898
Fold 4: MAE = 17965.477
Fold 5: MAE = 17711.010
Fold 6: MAE = 17828.323
Fold 7: MAE = 17917.331
Fold 8: MAE = 18137.332
Fold 9: MAE = 17717.272
Fold 10: MAE = 18058.658
Average MAE: 17914.18

In [ ]:
# import math
# MSE = np.square(np.subtract(ytest,ypred)).mean() 
 
# RMSE = math.sqrt(MSE)
# print("Root Mean Square Error:\n")
# print(RMSE)

In [ ]:
df_sub.info()

In [ ]:
df_sub_reg = df_test1[['Id']]

In [ ]:
# len(ypred)

In [ ]:
df_test1.info()

In [ ]:
# df_sub_reg['SalePrice'] = ypred1

In [ ]:
df_sub_reg

In [ ]:
# df_sub_reg.to_csv('submission_reg1.csv',index=False)